version: '3'
services:
  srv1:
    image: centos:latest
    command: ['python', '-m', 'SimpleHTTPServer', '8989']
    ports:
     - "8989:8989"
    networks:
     - stack-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 1s
        window: 5s
  srv2:
    image: centos:latest
    command: ['python', '-m', 'SimpleHTTPServer', '8990']
    ports:
     - "8990:8990"
    networks:
     - stack-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 1s
        window: 5s
  srv3:
    image: centos:latest
    command: ['python', '-m', 'SimpleHTTPServer', '8991']
    ports:
     - "8991:8991"
    networks:
     - stack-net
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 1s
        window: 5s

networks:
  stack-net:
    external:
      name: lab-network

